# Generated by Django 3.0.6 on 2020-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
