# Generated by Django 3.0.6 on 2020-05-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softlab', '0003_auto_20200525_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='likes',
            new_name='hobbies',
        ),
    ]
